supplier_name:      ASD s.r.o.
supplier_street:    Nová 5
supplier_city:      Ostrava
supplier_zip:       700 00
supplier_state:     Česká republika
supplier_ico:       514324584
supplier_dic:       CZ514324584
supplier_phone:     '-'
supplier_email:     d.stroch@gmail.com
supplier_bank:      Komerční banka a.s.
supplier_bank_acc:  554521555/0100
supplier_swift:     '-'
supplier_iban:      '-'
signature_name:     'Jan Novák'
